name: snowflake_cicd_process

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup python 3.8x
      uses: actions/setup-python@v2
      with:
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Generate Coverage Report
      run: npm run coverage

    - name: Upload Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./coverage
